### PR TITLE
fix issue 325 to prevent az390 abort due to invalid DC field terminator

### PR DESCRIPTION
**Pull request by dsh33782**
This is a simple insert of a few lines of code in az390.java to issue error message 54 instead of hanging up when DC statement has invalid terminator after data field.

### CODE REVIEW

**Comment by dsh33782** [comment]
I think I've resolved conflict with Abe's change to az390 by moving my update log comment ahead of his.
So now I think all this pull needs is an approval to proceed with v1.8.02 release.

**Review by abekornelis — COMMENTED** [review]
Looks okay to me, but I'll leave it to John to give or withhold his approval.

**Comment by dsh33782** [comment]
Abe this pull is on hold until you, John, and I can agree on how to resolve differences about your previous pull which included update to az390 but also included changes regarding file paths if notiming option was specified.  After reviewing your changes again, I agree with John that your change should be removed before this change is applied.  I'm also attaching to test files for this pull
[TEST#325.MLC.TXT](https://github.com/z390development/z390/files/8693578/TEST.325.MLC.TXT)
[TESTDC3E.MLC.TXT](https://github.com/z390development/z390/files/8693580/TESTDC3E.MLC.TXT)

**Review by jyganci — APPROVED** [review]

**Review by abekornelis — APPROVED** [review]
fine by me.

**Comment by dsh33782** [comment]
Abe I could not find any option to do squash merge?

**Pull request merged**
