### PR TITLE
Release 1.8.1-rc.2 changes

### PR DESCRIPTION
**Pull request by adelosa**
Updates to be added prior to rc2 release.

### CODE REVIEW

**Review by abekornelis — DISMISSED** [review]

**Comment by adelosa** [comment]
@abekornelis - I have updated the bat job as directed by @jyganci. If you can approve this, I'll make this the v1.8.1-rc.2 release.

**Comment by jyganci** [comment]
Anthony,

Don wants the 2 echo "Verify ..."  lines deleted. That's lines 30 and 31 of
your RUNASMDEMOS.BAT:

echo "Verify demo\TESTDCB1 copied demo\TESTDCB1.TF1 to demo\TESTDCB1.TF2"
 echo "Verify demo\TESTDCB1 wrote to demo\TESTDCB1.TF3"

Please do this.

Regards,

John Ganci

**Review by abekornelis — DISMISSED** [review]

**Comment by abekornelis** [comment]
I've approved assuming the last change request by Don/John will be fixed before the merge is done.

**Comment by adelosa** [comment]
@abekornelis -- Unfortunately once I push any changes, it cancels any approvals. 
@jyganci  - I have commented out the offending lines as per your previous comment. Can you approve the pull.

**Review by jyganci — APPROVED** [review]

**Review by abekornelis — APPROVED** [review]

**Pull request merged**
