### PR TITLE
is434 fix for ED instruction handles alternate signs incorrectly

### PR DESCRIPTION
**Pull request by jyganci**

### CODE REVIEW

**Review by dsh33782 — DISMISSED** [review]
I reviewed the changes and did not see any errors, but have not run the tests.

**Review by abekornelis — DISMISSED** [review]

**Comment by jyganci** [comment]
I want to add a groovy test. Must wait until I resolve problems with my git clone branches that arose after attempting to re-synchronize after merging the CODEPAGE pull request.

**Review by abekornelis — APPROVED** [review]
still looks okay to me. Good to see you're making progress ;-)

**Comment by jyganci** [comment]
The only changes are (1) moved position of the TEDIT test in rt/bash/runasmtests, rt/bat/RUNASMTESTS and (2) added new TEDIT test to the groovy RunAsmTests.groovy. Will wait for Anthony to give the changes a quick look over before doing the merge.

**Comment by adelosa** [comment]
Looks good to me @jyganci

**Comment by jyganci** [comment]
Okay,. My main concern (after the "push" questions) is the groovy test
script. Pretty simple addition, but I could not test it. Will know soon
enough when RunAsmTests.groovy runs.

**Comment by adelosa** [comment]
@jyganci - you can run the tests locally by using the following command from the z390test directory 
`./gradlew test` 
This will download any required components and run the tests.
If you use an IDE you can actually individually run specific tests once it is setup.
The green "Play" buttons next to the test methods will run the tests.
image

**Comment by jyganci** [comment]
I'll look into trying this. Thanks.

**Pull request merged**
