### PR TITLE
Changes by Dave Kienow

### LINKED ISSUE #180: RPI 1606: tz390 circular references in options file
Raised by Abe Kornelis 2017/01/29
Circular reference of options file causes unspecified exception in tz390

### LINKED ISSUE #192: RPI 1618: Separate sequential output file handling from z390
Raised by Abe Kornelis 2018/04/25
Create zoutput object to separate sequential output file handling from the main body of z390 classes

### LINKED ISSUE #195: RPI 1622: Issue S0D3 when executing TRAP2/TRAP4 instructions. Not supported.
Raised by Dave Kienow 2018/08/01
Issue S0D3 when executing TRAP2/TRAP4 instructions; S0C2 for as yet unsupported privileged instructions: CSCH, CSP, CSPG, DIAGNOSE, ESEA, HSCH, IDTE, IPTE, ISKE, LASP, LCTL, LCTLG, LPSW, LPSWE, LPTEA, LRA, LRAG, LRAY, LURA, LURAG, MSCH, PALB, PCKMO, PFMF, PGIN, PGOUY, PTAB, PTF, RCHP, RRBE, RRBM, RSCH, SAL, SCHM, SCK, SCKC, SCKM, SCKPF, SIGP, SPT, SPX, SSCH, SSKE, SSM, SSTPS, STAP, STCKC, STCRW, STCTG, STCTL, STFL, STIDP, STNSM, STOSM, STPT, STPX, STRAG, STSCH, STSI, STURA, STURG, TB, TPI, TPROT, TRACE, TRACG, TSCH, XSCH

### PR DESCRIPTION
**Pull request by abekornelis**
fixes #180 RPI 1606  Circular reference of options file causes unspecified exception in tz390
fixes #192 RPI 1618  Create zoutput object to separate sequential output file handling from the main body of z390 classes
fixes #195 RPI 1622 Issue S0D3 if any of the privileged instructions are used

### CODE REVIEW

**Comment by jyganci** [comment]
Just completed reading through all the changes. Some observations.

1. I would say that 90% of the changes were removing trailing blanks from lines.
2. Adding the privileged instruction exceptions was good.
3. Most of the added code pertained to the file I/O. The new class, zoutput.java, still has boolean variables debug and debug_trace set to true, so a lot of debugging output might appear.
4. There were a few "TODO" lines for things left undone.

Has the code been tested? Is it ready to be put in production?

I didn't really see anything wrong but items 3 and 4 concern me.

**Comment by abekornelis** [comment]
@jyganci Thanks for the review. You have paid more attention to detail than I have.
The whitespace issue was a known one - luckily you can set the comparison to ignore whitespace changes :-)
I share your concerns about the debug settings - I have turned them off.
The TODO items were not too relevant. I have changed the comments to indicate the function of the statements underneath.
I'm a bit hesitant about really removing debug code - we may need it sometime in the future.

As for testing: I have no idea how extensively Dave tested his changes.
they were built in 2018. For now I merely want to integrate it properly into the main line.
If any problems ensue we'll forward-engineer them into proper solutions.

**Review by dsh33782 — DISMISSED** [review]
Looks ok, but I'm approving in order to hopefully allow merge into test branch which can then be downloaded and tested since automated rt process is not yet available.

**Comment by dsh33782** [comment]
On June 12 email post after building test_abe branch with DaveK i/o changes:

Abe, all

The specific problem I saw with running demo\DEMOM8Q1.ZSM using your cloned z390_abe branch, is that that the step failed not finding ZSM instead of MLC.  I renamed it to MLC and it ran ok.

The RUNCBLDEMOS.MLC had the following recursive I/O error on zcobol\demo\HELLO.CBL:

 W:\dsh6w\test_abe>rem CBLCLG translate CBL to MLC, assemble, link, and exec using z390

W:\dsh6w\test_abe>echo off
10:05:27 HELLO     ZC390 START USING z390 V1.7.07 ON J2SE 1.8.0_261 06/12/21
10:05:27 HELLO     ZC390 ENDED   RC= 0 SEC= 0 MEM(MB)= 12 IO=2
10:05:27 HELLO     MZ390 START USING z390 V1.7.07 ON J2SE 1.8.0_261 06/12/21
MZ390I aborting due to recursive abort for I/O error on BAL write - java.lang.NullPointerException
10:05:27 HELLO     MZ390 ENDED   RC=16 SEC= 0 MEM(MB)=107 IO=475
Press any key to continue . . .
Press any key to continue . . .

The other zcobol demos also failed with same i/o error.

I’m not sure where we go from here.

**Comment by abekornelis** [comment]
I'm closing this pull request: there's too much work still undone. We'll need to move *all* file-related code into the zFile class. Interfaces into routines need to be cleaned up to avoid the use of shared variables. Many methods that will be copied over from other z390 source modules will become orphaned. Those orphaned methods will need to be removed.

**Pull request closed without merging**
