### PR TITLE
Is447 Synchronize bash and bat files used for regression testing

### PR DESCRIPTION
**Pull request by jyganci**
The Linux/Mac and Windows regression test have not been kept in sync. Issue #447 synchronizes the bash and bat directories. The Linux/Mac regression tests in the bash directory are moved to the rt/bash directory. The bash/readme.txt file is updated to reflect these moves. A git problem due to the old bash/readme.txt file having Windows line endings forced me to replace it with a new file, bash/readme-2.txt. At some point in the future, someone may be able to find a way to delete bash/readme.txt and rename bash/readme-2.txt to bash/readme.txt.

### CODE REVIEW

**Comment by adelosa** [comment]
My new test framework would solve this issue as you create using groovy and will work in Windows and *nix.

**Comment by adelosa** [comment]
I'll see if I can fix the readme.

**Review by adelosa — COMMENTED** [review]
See https://github.com/adelosa/z390/tree/is447 -- Its this branch with the readme file updated. I did not have any issues updating it so I do suspect its the config you have on your machine which is ignoring the line endings.. My mac has no special settings for line endings. Review your git config -l when in the dir.

**Comment by jyganci** [comment]
Results of "git --version" and "git config -l"

$ git --version
git version 2.34.3
$
$ git config -l
user.name=REDACTED
user.email=REDACTED
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
***@***.***:jyganci/z390.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
$

Do not see anything about line endings.

Regards,

John Ganci

**Comment by adelosa** [comment]
@jyganci -- Just responding to your email today. I am happy to approve, but please update bash/readme.txt and remove bash/readme-2.txt files. I would prefer to have the wrong line endings over duplicated files if you can't correct it. We can fix the line endings later.

**Comment by jyganci** [comment]
I have replaced bash/readme.txt and deleted bash/readme-2.txt. Pushed
changes to my fork. Please review.

Alas, now my clone is no longer usable.:For anything. See following. Will
have to clone again from my fork and hope for the best.

============================================================
$ git branch
  is447
  is451
* main
$ git checkout is447
error: Your local changes to the following files would be overwritten by
checkout:
bash/readme.txt
Please commit your changes or stash them before you switch branches.
Aborting
$
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
modified:   bash/readme.txt

no changes added to commit (use "git add" and/or "git commit -a")
$
$ git restore bash/readme.txt
$
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
modified:   bash/readme.txt

no changes added to commit (use "git add" and/or "git commit -a")
$
============================================================

**Review by abekornelis — DISMISSED** [review]
I've browsed the changes - though I'm no good at bash I did notice the comments. Which are valuable. And I saw all changes passed the tests during the push operation. So to my mind these changes should be a nice step forward and at least good enough.

**Comment by jyganci** [comment]
This pull request has been languishing since last September. All it does is move bash scripts to directories so their residence is consistent with where the corresponding bat files reside. Yes, I know the new test framework obsoletes the scripts and bat files. It is my understanding that we would keep the bash and bat scripts for the time being. Am I wrong?

If no one is going to approve this, please tell me and I will delete the PR.

**Review by abekornelis — APPROVED** [review]
John,

from memory - I think we stated indeed that users should be able to run the tests outside of the test framework. I am okay with implementing these changes. Please go ahead, John!

**Pull request merged**
