### PR TITLE
#335 acall

### PR DESCRIPTION
**Pull request by dsh33782**
This pull will update mz390 and tz390 to correct acall parm support issue #335.

### CODE REVIEW

**Comment by adelosa** [comment]
Looks like this change has broken the build. The Windows and Linux builds have both failed. 
You can run the same process by running BUILD.BAT on Windows in the project root folder to check that your changes are not impacting the build.
Here is the error being received - REPRO does not build:
```
REPRO     MZ390 START
MZ390E abort 84 file=10 line=41 internal system exception - java.lang.StringIndexOutOfBoundsException: String index out of range: -2
AZ390E error 198      (4/209)87            LAY   R12,4096(R13)   RPI 601
AZ390E error 198      (4/210)88            USING REPRO+8+4096,R12
AZ390E error 198      (6/34)100            MVC   INIT-2(2),*+10
AZ390E error 198      (6/35)101            B     INIT
AZ390E error 198      (6/34)106            MVC   GET-2(2),*+10
AZ390E error 198      (6/35)107            B     GET
AZ390E error  98      (7/63)135            CLI   BUILDAIX,TRUE
AZ390E error 198      (7/65)136            BC    15-EQ,#@IF_1_2
AZ390E error 198      (6/34)139            MVC   PUT_AIX_SORT_REC-2(2),*+10
AZ390E error 198      (6/35)140            B     PUT_AIX_SORT_REC
AZ390E error 165     (10/41)144   * MZ390E abort 84 file=10 line=41 internal system exception - java.lang.StringIndexOutOfBoundsException: String index out of range: -2
REPRO     MZ390 ENDED   RC=16 MEM(MB)= MB IO=2164
asml: mz390 error; mz390 rc=16; see errors on mz390 generated linklib/REPRO.BAL file and console
```

**Comment by adelosa** [comment]
So @dsh33782 - I assume you were looking for a review. I have reset you as assignee and added @abekornelis @dakienow and @jyganci as reviewers. Also, this request incorporates the #343  updates so we can just merge this one and ignore/close PR #344.

**Comment by dsh33782** [comment]
Anthony

 

Ok, thanks.

 

Don Higgins

 ***@***.***> ***@***.***

www.don-higgins.net

**Comment by jyganci** [comment]
Don, all

I assume you're lookin at this. Here's my 2 cents.

Looking at REPRO.BAL generated by the last time I successfully ran
build.sh, I see that the MZ390E error message is generated in mz390.java,
subroutine process_mz390, in a try-catch block. The try calls process_mac.
the catch produces the "abort 84" error message.

Looking at the REPRO.BAL listing, line 144 I see

139         MVC   PUT_AIX_SORT_REC-2(2),*+10
140        B     PUT_AIX_SORT_REC
141       DC    S(*+2)
142 *MEXIT #=     7 LV= 1 PM
143 *MCALL #=     8 LV= 1          ELSE
144 *MCALL #=     9 LV= 2          ZSTREQU

Maybe this helps.

Regards,

John Ganci

**Comment by dsh33782** [comment]
John

 

Thanks, yes that is exactly where I’m looking.

 

Don Higgins

 ***@***.***> ***@***.***

www.don-higgins.net

**Comment by dsh33782** [comment]
Anthony, all

 

Pull request #347 now pending to fix acall error - build.bat now runs on
local PC

 

Don Higgins

***@***.*** ***@***.***> 

www.don-higgins.net

**Comment by adelosa** [comment]
Closing - changes incorporated into #347

**Comment by abekornelis** [comment]
Don,

I've approved the merge request. I'll leave the actual merge to you.

Kind regards,
Abe
===



Op 08/02/2022 om 18:49 schreef dsh33782:

**Pull request closed without merging**
