### PR TITLE
IS458: B2C and X2C changes for issue 458

### PR DESCRIPTION
**Pull request by jyganci**
Modify mz390.java B2C code for similar X2C problem previously fixed. Also modify X2C code to round number of bytes to a multiple of 2. Add test program TB2CX2C.MLC to test the changes.

### CODE REVIEW

**Comment by adelosa** [comment]
[Add_TB2CX2C_to_framework_tests.patch](https://github.com/z390development/z390/files/11611291/Add_TB2CX2C_to_framework_tests.patch)
Here is a patch to add the test module to the test framework. I tried pushing to your fork but got a permission error.

**Comment by jyganci** [comment]
Thanks. I've never done a patch before so will have to read up on it.

Alternatively, I may just do a commit of the change. I've hesitated doing
groovy changes since I can't test them on my PC.

Will take care of this soon.

**Review by dsh33782 — DISMISSED** [review]
John, I reviewed the code and did not see any errors, but have not run any independant tests.

**Comment by jyganci** [comment]
Anthony, I finally added your patch to the groovy script. Since I cannot test groovy on my PC, please give it a quick look. Thanks.

**Review by abekornelis — APPROVED** [review]
looks okay to me.

**Pull request merged**
