### PR TITLE
Release 1.7.8 alpha.1 distribution fixes

### PR DESCRIPTION
**Pull request by adelosa**
This pull request addresses issues related to the initial 1.7.8-alpha.1 release.

Items addressed:
* Updated release changelog to new format
* Added README.txt file with info as per @dsh33782 request
* Removed the bldjar/BLDJAR.BAT from dist
* Added the bsam folder so runrtbsam script works

### CODE REVIEW

**Review by dsh33782 — COMMENTED** [review]
Anthony, I've looked at file changes and have following comments:
1.  I like the readme.txt file
2. I would like to see the rt\bat\zopcheck.bat added to the bat\runasmtests.bat
3. It looks like the bsam files have been added including the new cpy*.* files but the corresponding new cpy*.* and updates to all the files in qsam directory.  These changes correct a number of errors flags by John previously.
4. I think more clarifiation should be added about java 8+ runtime is all that is needed to use z390 distribution, but java 8+ jdk is required to run bat\bldjar.bat to rebuild z390.jar if src dir is added back.  Also note bldjar includes option "source 8" indicating z390 current java source level. 

I know I've changed my mind and I'd be happy to discuss any of these if you disagree.

**Comment by adelosa** [comment]
Adding comments from @jyganci here from Google Groups for full visibility.
CHANGELOG.md
1. Before commenting, I'd like to see what the new page you created on your github account looks with these changes.

README.txt
1. Line 20. "For Linux/MacOS users, ... your Windows Path". Remove "Windows".
2. Lines 37-38. "Run bat/BLDCBLLIB.BAT ...". BUILD.BAT and build.sh do this. These lines can be deleted.
3. As far as "verification" goes, the steps listed here seem adequate to me. However, Don ran the BSAM and QSAM tests (and found problems). Should these tests be added?

I strongly disagree about not including the source as part of the distribution, but accept your decision to do so.

I disagree about removing bldjar. If the user later decides to download the source, the bldjar file will be needed.

**Comment by adelosa** [comment]
@jyganci The bldjar file is not deleted, just not included in the distribution because if you want to build, you should clone the repository using Git. It is still part of our source and is available.
I will also see if I can generate a GitHub release on the branch so you can see the release info.. but it will just have the text from CHANGELOG.md in the release details.

@jyganci @dsh33782 - It seems that the contents of the release distribution are still a point of contention. 
Sounds like you want the whole source with a jar.. It is not what I would do as you can see.. but if that is the will of the people, I'll just build it the way you want it. 
Just be aware if you build the jar outside of Git, the version will be "Uncontrolled" and they will need to use FORCE on the bldjar command to make it compile.

There are a few typos I need to fix. If you want to suggest wording changes in the README.txt and CHANGELOG.md files, I would be happy to include.

**Comment by jyganci** [comment]
I, of course, meant that bldjar  was deleted/removed from the release, not
the repository.

**Comment by jyganci** [comment]
One option is to do the release without the source (that is, as it is in alpha 1) and see what the users say.

**Comment by adelosa** [comment]
From @jyganci via Google Groups
The alpha.2 version looks good to me. A few nit typos in README.txt:

1. Lines 37-39. "DEMO\" -> "demo\".
2. Lines 43-48. "ZCOBOL\DEMO\" -> "zcobol\demo\".
3. Lines 53-58. "TESTS\" -> "tests\".
4. Line 53. Remove extra space (there are 2 before the dash). "... MLC  - verify ..." -> "... MLC - verify ...".
5. Line 59. "RT\BAT\" -> "rt\bat\".
6. Lines 61-62. Comment/observation only. Lines 51-52 are followed by a list of the assembler tests. There are no such lines for the COBOL tests. Intentional?

**Comment by adelosa** [comment]
I have applied fixes as per John's suggestions. See 0958229

> 6. Lines 61-62. Comment/observation only. Lines 51-52 are followed by a list of the assembler tests. There are no such lines for the COBOL tests. Intentional?

@jyganci - the content was in the old README.txt file and I have just added some headings but the content is existing.
If someone wants to suggest some content, I would be happy to add it in.

Just as a side note, I am planning that once the markdown doco is completed (see #315), we can then:
1. Point people to the GitHub documentation for details on using, building and contributing to the project -- Like draft at https://adelosa.github.io/z390/
2. The distribution build process will incorporate a conversion of the markdown into a PDF doc that would be included in the distribution.

**Comment by adelosa** [comment]
@dsh33782 or @jyganci 
I think this pull request is good to go. There does not seem to be further comments regarding the contents of the distributions (lets see what comments we get on the beta).
Can I request an approval on this pull request so I can merge these changes and start generating the beta's off the main repo rather than my fork. Any additional fixes and enhancements for the release can be added via the standard pull request process. This request was just to make sure the build process was addressing the issues required before a beta release.
Once merged I can generate new betas and real releases as required on the main repo.
Any questions let me know.

**Review by jyganci — APPROVED** [review]
Looks good to me. Nice job cleaning up and simplifying the bash scripts.

**Pull request merged**
