### PR TITLE
Issue#245

### PR DESCRIPTION
**Pull request by dsh33782**
CICS has been updated to correct missing bat path in cics startup commands, and sz390.java has been corrected to only invoke new zvsam code when opt_zvsam option is set to 2.  The default opt_zvsam = 1 is the default.  With these changes all the cics programs can be rebuilt using cics\bat\dfhall and dfhallv.  A cics regions can be started with cics\bat\z390cicg.  A remote terminal can be started via cics\bat\z390kcpr in separate command prompt.

### CODE REVIEW

**Comment by adelosa** [comment]
Encountering issues running DFHALLV.BAT.
Running straight after running DFHALL.BAT successfully.

Part of Bat job failing.

    rem BUILD THE VARIABLE ESDS
    SET INFILE=%CICSPATH%\MYFILE1V.TXT[RECFM=VT]
    SET OUTFILE=%CICSPATH%\Z390CAT1.MYFILE01
    CALL bat\EZ390 LINKLIB\REPRO %1

At end of job, there is no file names z390CAT1.MYFILE01 in the VSAM folder.

Output messages

    14:34:56 REPRO     EZ390 START USING z390 V1.7.07 ON J2SE 14.0.2 10/01/21
    REPRO z390 VSAM UTILITY V1.2
    REPRO LOADING VSAM FROM QSAM INFILE
    REPRO OPENING VSAM OUTFILE FOR RELOAD VS MOD
    zACB constructed
    Open invoked
    EZ390I Trace Table Entry      800FEF70 4770D9B2     BNE
    EZ390I Trace Table Entry      800FEF8A 47F0D982     B
    EZ390I Trace Table Entry      800FEF5A 47F0D53A     B
    EZ390I Trace Table Entry      800FEB12 9501C6CC     CLI
    EZ390I Trace Table Entry      800FEB16 4770D586     BNE
    EZ390I Trace Table Entry      800FEB5E A715001A     BRAS
    EZ390I Trace Table Entry      800FEB92 0A23         SVC
    EZ390I Trace Table Entry      800FEB94 4110C638     LA
    EZ390I Trace Table Entry      800FEB98 41000020     LA   
    EZ390E error  11 ABEND PSW=07851600 800FEB9C 0A13         SVC   ABEND S0C5
     R0-R3 0000000000000000 F4F4F4F4000FDF98 F4F4F4F4000FE5FF F4F4F4F4F4F4F4F4
     R4-R7 F4F4F4F4F4F4F4F4 F4F4F4F4F4F4F4F4 F4F4F4F4F4F4F4F4 F4F4F4F4F4F4F4F4
     R8-RB F4F4F4F4000FE560 F4F4F4F4000FE580 F4F4F4F4F4F4F4F4 F4F4F4F4F4F4F4F4
     RC-RF F4F4F4F4000FF5D8 F4F4F4F4800FE5D8 F4F4F4F400002018 F4F4F4F400000000
    EZ390E error  12 program aborting due to abend S0C5
    14:34:56 REPRO     EZ390 ENDED   RC=16 SEC= 0 MEM(MB)= 16 IO=220 INS=131

What am I doing wrong??

**Comment by adelosa** [comment]
Just for the record - the issue above was caused by the Jar file not being recompiled with the changes contained in the pull request. Ran bldjar to get new build and reran. VSAM file load was OK then. 
Have another issue now when trying to start the CICS server using cics/bat/Z390CICG.BAT
Details in google groups area.

**Comment by adelosa** [comment]
These changes were included in PR #326. Closing.

**Comment by dsh33782** [comment]
This issue has been fixed in Alpha2, removing from project v1.8.0

**Pull request closed without merging**
