### PR TITLE
ASSIST XDECI and XHEXI Is291 is305

### PR DESCRIPTION
**Pull request by jyganci**
Issue #291 and issue #305: (1) Fixes for the ASSIST instructions XDECI and XHEXI. (2) New assembler programs to test the changes. Note that the test programs accept a PARM value, lowercase v, that results in "verbose" output describing each test performed. If the PARM value is omitted, only summary statistics are printed. (3) Update bat/RUNASSIST.BAT and bash/runassist to invoke the test programs using "verbose".

### CODE REVIEW

**Review by adelosa — CHANGES_REQUESTED** [review]
Hi @jyganci -- this is great and I love the test cases..  

I pulled down your branch, rebuilt the jar based on your code and then ran the bash/runassist script.
It all worked. 

I then I changed the expected value of one of the tests to something wrong and reran it. 
It detected the error, but the job was still successful (RC=0)

For the automated build to be useful, it needs to tell you when a test fails.
The test programs should return a non zero return code so that the build will stop with an error, otherwise we will never know it is broken.

I am not sure how to do this in an assembler program, but I am sure you will.
**edit** OK, so the value in R15 at exit is the RC value..

My other comments were around copyright.. I would like to do a bulk update on the copyright notices before our first 1.8 release so don't worry about that one.

**Comment by jyganci** [comment]
Anthony,

Thanks for testing. Yes, the test programs always have a return code of
zero. I'd thought about that at one point, but decided that since the user
would see the error, there was no need. I was not thinking of running them
in automation.

It will be an easy fix to create a non-zero return code when an error
occurs. I'll try to get to it today (my today) but I want to finish up some
of the cics stuff I started.

Regards,

John Ganci

**Comment by jyganci** [comment]
The changes have been made and pushed to my fork. TSTXDECI and TSTXHEXI now set the return code to 8 if there is at least one error. Tested each program with  "no errors" and "at least one error".

**Comment by adelosa** [comment]
Looks good and happy to approve. I had a go at fixing myself for my own learning. I was on the right path but my instruction vocab is not that good. The register restore caused me the issues. I was at least at the right part of the program.

**Review by adelosa — APPROVED** [review]

**Pull request merged**
