### PR TITLE
Move to Java 11 for automated build and package

### PR DESCRIPTION
**Pull request by adelosa**
This pull request is updating the automated builds to move from Java 8 to Java 11.

* Java 11 is the next long term support Java version after Java 8 -> extended support until 2026.
* Java 17 is the current LTS Java version providing extended support until 2029 - released Sept 2021.

This also includes a move to from AdoptOpenJDK to Eclipse Temurin Java. Same Java, just new project home/governance.
See https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/ for details

### CODE REVIEW

**Review by dsh33782 — DISMISSED** [review]
Looks good to me.  No negative feedback on change from z390 group.

**Comment by jyganci** [comment]
I did not get an email notification of any comment posted to the z390 users group. Looking at the z390 google group, I only see Don's 11/10/2021 post about the LARL problem. Previous post was 9/17/2021. Nothing about moving to Java 11. How was the group notified about Java 11?

**Comment by dsh33782** [comment]
John, all

 

You are right, I was thinking about LARL issue which is separate from Java 11.  I will post a message  to z390 group now.

 

Don Higgins

 ***@***.***> ***@***.***

www.don-higgins.net

**Comment by jyganci** [comment]
Anthony, the Oracle page for Java 17,
  https://www.oracle.com/java/technologies/downloads/
says that "JDK 17 will receive updates under these terms, untill at least September 2024". You said "Java 17 is the current LTS Java version providing extended support until 2029 - released Sept 2021." Where did you get the 2029 date? Is "extended support" different from "receiving updates"?

**Comment by adelosa** [comment]
Support dates here.
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by jyganci** [comment]
The following sentence is on that link: (Bolding added)

Dates listed below apply only to the* commercially supported* Oracle JDK
releases available to Oracle Customers.

These dates do not apply to non-paying users.

They way I interpret this is that for me, according to the JDK 17 download
link at

https://www.oracle.com/java/technologies/downloads/#java17

JDK 17 will only receive updates until September 2024, not 2026.

All I can find about OpenJDK 11 for non-paying users is at

https://adoptium.net/support.html?variant=openjdk11&jvmVariant=hotspot

where it states that JDK 11 will be supported until at least October 2024.

For me, nailing down JDK end of support dates is non-trivial.

Regards,

John Ganci

**Comment by dsh33782** [comment]
This pull to implement java 11 as base for z390 builds has gotten stuck.  I did post message to z390 user group on 11/11/21 titled "Recommendation to move from Java 8 to Java 11 for future z390 builds".  There has not been a push to remain on Java 8 so I would like to go ahead and make this move.  Perhaps the strongest reason is that Java 11 is the recommended version for free Visual Studio Code which supports Java, HLASM, and GIT.  Both Java 8, 11, and 17 are all labelled as Long Term Support (LTS) so it seems safe to believe Java 11 will be supported for at least the next year.  We can revisit the Java support issue again then.  Reference:
    https://adoptium.net/support.html?variant=openjdk11&jvmVariant=hotspot

**Review by dsh33782 — DISMISSED** [review]
I did go back through email and found where I posted to z390@googlegroups.com on 11/11/21 and receieved my own copy back.  Since then I have not gotten any feedback from z390 users on the group about the change.  I'm approving move to Java 11 so we will be up to version recommended by Visual Studio Code which supports HLASM, Java, and Git.

**Review by jyganci — APPROVED** [review]
Approve but would like the z390 community to know when any Java code specific to Java 11 is added.  My Linux PC and MacBook will continue to use Java 8, so I would appreciate some advance notice if/when Java 11 code is used in the z390 source.

**Comment by adelosa** [comment]
Closing this request.. Will submit new request once decision is made regarding Java version to target.

**Comment by jyganci** [comment]
If this page

https://endoflife.date/java

is accurate,

1. Java 8 (LTS)
1.1. Support ended 31 Mar 2022
1.2. Security updates until 31 Dec 2030
1.3. Current version 8u371 (Oracle restricted license; last free was 8u201;
no OpenJDK???)

2, Java 11 (LTS)
2.1.Support ends 30 Sep 2023
2.2. Security updates until 30 Sep 2026
2.3. Current release 11.0.19 (Oracle restricted license; use OpenJDK
instead)

3. Java 17 (LTS)
3.1. Support ends 30 Sep 2026
3.2. Security updates until 30 Sep 2029
3.3. Current release 17.0.7 (back to a free version)

All current releases were available 18 Apr 2023.

Since my test running (z390 built with Java 17) on Java 8 failed, I did one
more test. Downloaded z390_v1.8.1.zip from the github link; built with Java
11 I think. Repeated Java 8 test. It worked. Also worked running with Java
17.

So it looks like we could keep using Java 11 on github for the build, which
allows users to have Java 8 (or higher). My Java 8 is at 8u201, never to be
upgraded due to the restrictive Oracle license, so the 31 Dec 2030 end date
for security updates is irrelevant to me.

Should we poll the user list? Based on previous polls, I do not expect many
replies.

Finally, when I downloaded z390_v1.8.1.zip I noticed it was added May 24,
2022. Time for another release?

Regards,

John Ganci

**Pull request closed without merging**
