### PR TITLE
Issue #358: Fix breakpoint info displayed in test mode

### LINKED ISSUE #358: incorrect breakpoint info is displayed in test mode
the problem has been reported by Lin Lyons. He's working with an old version of z390, but the problem replicates on current version.
This is what Lin writes:

TEST  BREAK  ON  is not being displayed correctly when multiple break points are set.

Z390  V 1.5.06   at 80 years old, I wasn't able to understand the next suggested version.
I'm actually thinking that if I went backward 1-2 releases, it would be okay for me.
I don't need any of the latest changes.   I'm a pretty simple, old, guy.

I had thought that I couldn't set multiple break points, but that is wrong.
Test does set multiple break points.
BUT, when it hits any break point, it reports it as the last one set.
The break address is correct, but the   TEST BREAK ON  is always the last one set.  EG.

load location = FE000.
set 4 break points
first break point is hit correctly.
BUT  it's reported as that last break point that was set.
go continues to correctly hit the break points that were set, but always reported as the last one.

test cmd:  exit
test batch exit request

test cmd: a fe010.  first break point
 000FE010 *41A00FFF 41CAD001 58110000 48210000* * µ.? ­}.ì...ç?..*

test cmd: a fe014.  second break point
 000FE014 *41CAD001 58110000 48210000 4B20C380* * ­}.ì...ç?...?CØ*

test cmd: a fe018.  third break point
 000FE018 *58110000 48210000 4B20C380 4740D9A8* *ì...ç?...?CØå Ry*

test cmd: a fe01c.  forth break point
 000FE01C *48210000 4B20C380 4740D9A8 D200DB69* *ç?...?CØå RyK.ûÑ*

---  4 break points set,  now go.

test cmd: g
test break on a fe01c.  forth break point
 800FE010 0 41A00FFF     LA    RA=F4F4F4F4 S2(00000FFF)   <--- first break pt, reported as last.

----  The address (FE010) is correct, however the message indicates a different address (FE01C).

test cmd: g
test break on a fe01c.  forth break point
 800FE014 0 41CAD001     LA    RC=F4F4F4F4 S2(000FF000)

test cmd: g
test break on a fe01c.  forth break point
 800FE018 0 58110000     L     R1=00002300 S2(00002300)=00002304

test cmd: g
test break on a fe01c.  forth break point
 800FE01C 0 48210000     LH    R2=F4F4F4F4 S2(00002304)=0000

### PR DESCRIPTION
**Pull request by jyganci**

### CODE REVIEW

**Comment by adelosa** [comment]
Fixes #358

**Comment by jyganci** [comment]
This pull request is the fix for issue 358. I've edited the title to the pull request to contain the issue number. Is that sufficient?

**Comment by abekornelis** [comment]
John,

thanks - that does help to keep things together.

Kind regards,
Abe
===



Op 04/03/2022 om 17:40 schreef John Ganci:

**Review by abekornelis — APPROVED** [review]

**Review by dsh33782 — COMMENTED** [review]
Looks good to me.

**Pull request merged**
